services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
      
  app:
    build: .
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - redis